import type { Project } from "./types";

const now = "2026-04-10T00:00:00.000Z";

export const seedProjects: Project[] = [
  {
    id: "seed-dr-asael-venzor",
    slug: "dr-asael-venzor",
    title: "Dr. Asael Venzor",
    subtitle: "Brand & identity design",
    occurred_on: "2020-11-01",
    client: "Dr. Asael Venzor",
    role: "Brand & identity design",
    summary:
      "For this project, the goal was to craft a personal brand identity that conveyed the professionalism and expertise of our dentist client in Juarez, Chihuahua—without relying on any typical tooth imagery. We drew inspiration from the specialized “flap” technique frequently used in periodontics to treat gum recession. Noticing how the gum repositioning movement subtly mirrored the client’s initials, we incorporated this shape into the logo, creating a refined, meaningful design that the client loved. The result is a sophisticated brand identity that reflects the precision and care unique to his practice.",
    tags: ["identity"],
    accent: "#7A1F3D",
    specs: {
      Client: "Dr. Asael Venzor",
      Role: "Brand & identity",
      Medium: "Mark, stationery",
      Practice: "Periodontics, Juarez",
    },
    cover_path: "/work/dr-asael-venzor-05.png",
    blocks: [
      { type: "image", src: "/work/dr-asael-venzor-01.png", caption: "Wordmark" },
      { type: "image", src: "/work/dr-asael-venzor-02.png" },
      { type: "image", src: "/work/dr-asael-venzor-03.png" },
      { type: "image", src: "/work/dr-asael-venzor-04.png" },
      { type: "image", src: "/work/dr-asael-venzor-05.png", caption: "Stationery" },
      { type: "image", src: "/work/dr-asael-venzor-06.png" },
      { type: "image", src: "/work/dr-asael-venzor-07.png" },
      { type: "image", src: "/work/dr-asael-venzor-08.png" },
      { type: "image", src: "/work/dr-asael-venzor-09.png" },
      { type: "image", src: "/work/dr-asael-venzor-10.png" },
      { type: "image", src: "/work/dr-asael-venzor-11.png" },
    ],
    published: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "seed-black-diamond",
    slug: "black-diamond",
    title: "Black Diamond Drilling",
    subtitle: "Identity / website / merch design",
    occurred_on: "2021-03-01",
    client: "Black Diamond Drilling",
    role: "Identity, website, merch",
    summary:
      "Black Diamond is a family-owned business in the oil and gas industry looking to elevate their brand, taking it from a trusted local operation to a prominent global distributor. Through strategic collaboration, we redefined their positioning, enhancing their visual identity and brand presence to reflect their ambitions on the world stage.",
    tags: ["identity", "website", "merch"],
    accent: "#111111",
    specs: {
      Client: "Black Diamond Drilling",
      Role: "Identity, website, merch",
      Medium: "Mark, site, gear",
    },
    cover_path: "/work/black-diamond-01.jpg",
    blocks: [
      {
        type: "text",
        body: "The previous logo carried years of history but limited the company’s visual presence. Our redesign aimed to open the door to a timeless and enduring identity — one that reflects both legacy and modern strength. Using a bold, all-caps typeface, we conveyed power, trust, and stability. At the center of the design, the newly crafted diamond icon symbolizes passion and integrity — core values that define Black Diamond Drilling. Positioned at the heart of the logotype, the diamond embodies the family’s care for their business and the enduring trust they’ve built within the industry.",
      },
      { type: "image", src: "/work/black-diamond-01.jpg", caption: "Identity" },
      { type: "image", src: "/work/black-diamond-02.gif" },
      { type: "image", src: "/work/black-diamond-03.jpg" },
      { type: "image", src: "/work/black-diamond-04.jpg" },
      {
        type: "text",
        body: "Custom iconography was designed specifically for their website categories. Meticulously forming a simplistic visual description of each category name without breaking design consistency.",
      },
      { type: "image", src: "/work/black-diamond-05.jpg", caption: "Iconography" },
      { type: "image", src: "/work/black-diamond-06.jpg" },
      { type: "image", src: "/work/black-diamond-07.jpg" },
      { type: "image", src: "/work/black-diamond-08.jpg" },
      {
        type: "text",
        body: "The success of the new identity inspired Black Diamond's owners to expand their brand into a merchandise line, launching a hat company that would house all their gear. This extension allowed their loyal customers to proudly represent the brand both on and off the field, further strengthening their connection with the community.",
      },
      { type: "image", src: "/work/black-diamond-09.jpg", caption: "Merchandise" },
      { type: "image", src: "/work/black-diamond-10.jpg" },
      { type: "image", src: "/work/black-diamond-11.jpg" },
      { type: "image", src: "/work/black-diamond-12.jpg" },
    ],
    published: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "seed-my-vida-skin",
    slug: "my-vida-skin",
    title: "My Vida Skin",
    subtitle: "Identity & packaging design",
    occurred_on: "2021-10-01",
    client: "My Vida Skin",
    role: "Identity & packaging design",
    summary:
      "A returning client approached me with a bold vision to disrupt the cosmetic industry by creating a brand that reconnects people with their natural beauty through pure ingredients. From this idea, My Vida Skin was born—not just a cosmetic brand, but a statement of self-empowerment. We developed a brand identity centered around choice, confidence, and authenticity, with the slogan “My Vida, My Skin” reinforcing skincare as a personal decision. By using natural ingredients, My Vida Skin gives women the freedom to choose what’s best for their bodies without compromise.",
    tags: ["identity", "packaging"],
    accent: "#C4A574",
    specs: {
      Client: "My Vida Skin",
      Role: "Identity, packaging",
      Medium: "Mark, type, pack",
      Line: "My Vida, My Skin",
    },
    cover_path: "/work/my-vida-skin-13.jpg",
    blocks: [
      {
        type: "text",
        body: "The brand identity reflects this vision with a bold yet inviting logo. A strong, modern typeface gives the brand confidence, while combined with a delicate script font adds a human, personal touch.",
      },
      { type: "image", src: "/work/my-vida-skin-01.gif", caption: "The logo" },
      { type: "image", src: "/work/my-vida-skin-02.gif" },
      { type: "image", src: "/work/my-vida-skin-03.png" },
      {
        type: "text",
        body: "To further emphasize inclusivity and purity, we curated a neutral color palette that resonates with the authenticity of all skin tones.",
      },
      { type: "image", src: "/work/my-vida-skin-04.jpg", caption: "Color palette" },
      {
        type: "text",
        body: "The chosen typeface is a bold, cosmopolitan style font that communicates the union of the brand in a bold, unapologetic way–one that demands attention yet welcomes with familiarity.",
      },
      { type: "image", src: "/work/my-vida-skin-05.gif", caption: "Typography" },
      { type: "image", src: "/work/my-vida-skin-06.png" },
      { type: "image", src: "/work/my-vida-skin-07.png" },
      { type: "image", src: "/work/my-vida-skin-08.png" },
      { type: "image", src: "/work/my-vida-skin-09.png" },
      { type: "image", src: "/work/my-vida-skin-10.png" },
      { type: "image", src: "/work/my-vida-skin-11.gif" },
      { type: "image", src: "/work/my-vida-skin-12.png" },
      {
        type: "text",
        body: "The packaging design was a unique decision as we stepped in as new players in such a competitive market. While many competitors leaned toward bright, oversaturated colors, we intentionally moved in the opposite direction to create a calmer, more authentic presence. To stay true to our brand’s natural essence, we selected bamboo lids — a material that visually and symbolically reinforces sustainability and purity. Paired with subtly glossy, transparent bottles, the design communicates both clarity and honesty, perfectly reflecting My Vida Skin’s commitment to natural beauty and transparency.",
      },
      { type: "image", src: "/work/my-vida-skin-13.jpg", caption: "Packaging" },
    ],
    published: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "seed-my-vida-origins",
    slug: "my-vida-origins",
    title: "My Vida Origins",
    subtitle: "Packaging design / product photography",
    occurred_on: "2022-06-01",
    client: "My Vida Origins",
    role: "Packaging, photography",
    summary:
      "I collaborated with a supplement brand targeting the Latino community, founded by two brothers passionate about sharing nature’s healing power. With a commitment to helping people prevent and address common health issues, they used strategically formulated supplements made from herbs, fruits, vegetables, and essential nutrients. Our challenge was to convey the brand’s unique, exotic ingredients with a premium, cohesive design that could seamlessly extend across future products while maintaining a distinct, recognizable look.",
    tags: ["packaging", "photography"],
    accent: "#1F6B3A",
    specs: {
      Client: "My Vida Origins",
      Role: "Packaging, photography",
      Medium: "Label system, social, photo",
      System: "4 → 13 products",
      Time: "70% faster to design",
    },
    cover_path: "/work/my-vida-origins-01.jpg",
    blocks: [
      {
        type: "text",
        body: "I designed a flexible labeling system that can easily be replicated onto any bottle of any size all while keeping the brand consistency in place. This new design cut down the design time by 70% and expanded the products from 4 to 13 in just 2 years. The company went from having a line up of inconsistent label designs, to a cohesive family of products that showed off the new face.",
      },
      { type: "image", src: "/work/my-vida-origins-02.gif", caption: "Label system" },
      { type: "image", src: "/work/my-vida-origins-03.jpg" },
      {
        type: "text",
        body: "Social media graphics played a key role in the brand’s expansion efforts and served as a powerful way to showcase the new identity. I designed a structured system for posts that complemented the brand’s visual style seamlessly. All content was written in Spanish to connect with our primary audience — the Hispanic community — while maintaining a refined, high-end aesthetic and skyrocketing brand engagement.",
      },
      { type: "image", src: "/work/my-vida-origins-04.jpg", caption: "Social" },
      {
        type: "text",
        body: "The photography was approached with a minimalistic approach – a style that would bring to focus to the face of the brand without any extra distractions. An essence that brought the consumer very close to product itself. Macro and close up shots, harsh shadows and solid color background were intentionally used to create this experience. The results was a beautiful symmetry of objective art direction and premium feel.",
      },
      { type: "image", src: "/work/my-vida-origins-05.jpg", caption: "Photography" },
      { type: "image", src: "/work/my-vida-origins-06.jpg" },
      { type: "image", src: "/work/my-vida-origins-07.jpg" },
      { type: "image", src: "/work/my-vida-origins-08.jpg" },
    ],
    published: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "seed-breneman-capital",
    slug: "breneman-capital",
    title: "Breneman Capital",
    subtitle: "Identity / website / ad creative",
    occurred_on: "2025-04-01",
    client: "Breneman Capital",
    role: "Identity, website, ads",
    summary:
      "Breneman Capital has built a strong reputation over two decades of real estate investment success. However, its legacy identity no longer reflected the firm’s forward-thinking strategies or expanding portfolio. The brand had become indistinguishable from other major players—blending in with dull gray-blues, cliché golds, and a logo that felt more conventional than intentional. Its visuals lacked emotion, distinction, and clarity. This project set out to reimagine the brand identity, revitalize its marketing assets, and create a cohesive visual language that would resonate with a new generation of investors—one that restored prestige, inspired trust, and reflected the bold evolution of the Breneman name.",
    tags: ["identity", "website", "ads"],
    accent: "#06283D",
    specs: {
      Client: "Breneman Capital",
      Role: "Identity, website, ads",
      Medium: "Mark, site, campaign",
    },
    cover_path: "/work/breneman-capital-02.jpg",
    blocks: [
      {
        type: "text",
        body: "The new logo embodies authority, heritage, and trust. Its deliberate stacked structure symbolizes Breneman Capital’s commitment to building solid foundations that reach greater heights. A powerful serif typeface conveys strength and longevity — a statement that says, “we’re here to build.” Complementing it, a clean sans-serif font brings balance, ensuring the brand remains modern and professional. The renewed icon pays homage to its predecessor while fulfilling its evolution with deeper symbolism and intent. And the refined monogram preserves the prestige and legacy of the full logo, adapting seamlessly for smaller-scale applications.",
      },
      { type: "image", src: "/work/breneman-capital-01.jpg", caption: "The logo" },
      { type: "image", src: "/work/breneman-capital-02.jpg" },
      {
        type: "text",
        body: "The icon was meticulously reengineered to preserve the essence of the original while evolving it to reflect the new brand. Using the curve of the capital “B,” the rising pillars gain a subtle arc — symbolizing both the upward movement of real estate appreciation and Breneman’s core value of continually striving for greater heights. By inverting the pillar colors and leveraging negative space as the primary visual plane, the design forms a three-dimensional structure with window-like details — a direct nod to the real estate world and the firm’s commitment to growth and innovation.",
      },
      { type: "image", src: "/work/breneman-capital-03.gif", caption: "The icon" },
      { type: "image", src: "/work/breneman-capital-04.gif" },
      {
        type: "text",
        body: "The color palette establishes a consistent look and feel that reflects Breneman’s mission of human-first investments. The soft pastel tones introduce warmth, approachability, and care — balancing perfectly with the bold, confident depth of the dark blue. Together, these colors communicate trust and competitiveness without losing humanity. This thoughtful blend not only appeals to discerning investors but also attracts team members who see Breneman as more than a company — they see a family.",
      },
      { type: "image", src: "/work/breneman-capital-05.jpg", caption: "Color palette" },
      { type: "image", src: "/work/breneman-capital-06.jpg" },
      { type: "image", src: "/work/breneman-capital-07.jpg" },
      {
        type: "text",
        body: "Our goal was to challenge the common perception of real estate as a purely profit-driven industry. We set out to reposition Breneman Capital as a human-first real estate firm — one focused on creating foundations that empower people to build the future. The copywriting strategy centered on genuine communication, speaking to people rather than just money-seeking firms. In terms of design, the softer colors and rounded corners throughout the website design make the firm feel more approachable, softening the experience and removing the sharp edges that might otherwise convey a sense of rigidity or inaccessibility.",
      },
      { type: "image", src: "/work/breneman-capital-08.jpg", caption: "Website" },
      { type: "image", src: "/work/breneman-capital-09.jpg", caption: "Ad creative" },
    ],
    published: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "seed-titan-drilling",
    slug: "titan-drilling",
    title: "Titan Drilling",
    subtitle: "Corporate identity / website",
    occurred_on: "2025-06-01",
    client: "Titan Drilling",
    role: "Corporate identity, website",
    summary:
      "Titan is a pioneering manufacturer and drilling operations company whose technologies have reshaped its position in the oil and gas industry. They came to me seeking a brand identity strong enough to match their innovation and reputation.",
    tags: ["identity", "website"],
    accent: "#1F7D53",
    specs: {
      Client: "Titan Drilling",
      Role: "Identity, website",
      Medium: "Mark, type, site",
      Type: "Switzer Variable",
    },
    cover_path: "/work/titan-drilling-cover.jpg",
    blocks: [
      { type: "image", src: "/work/titan-drilling-01.jpg", caption: "The Titan mark" },
      { type: "image", src: "/work/titan-drilling-02.jpg" },
      {
        type: "text",
        body: "The logo design pays tribute to Titan’s engineering precision. Built using the Fibonacci sequence, the mark embodies both structure and strength — a visual reflection of the company’s bold impact. The design represents the downward motion of a drilling operation, formed by two geometric blocks in a “T” configuration. Crafted with perfect proportion through Fibonacci ratios, the result is a mark that feels balanced, intentional, and visually satisfying to the eye.",
      },
      { type: "image", src: "/work/titan-drilling-03.gif" },
      {
        type: "text",
        body: "Switzer Variable is the chosen font to give face to the Titan brand. It is a variable font that is fierce and commandful when in heavy weight, yet professional and relatable when using it in lighter weight. It is the perfect font family to that supports the voice and personality of Titan.",
      },
      { type: "image", src: "/work/titan-drilling-04.jpg", caption: "Typography" },
      { type: "image", src: "/work/titan-drilling-05.jpg", caption: "Color palette" },
      { type: "image", src: "/work/titan-drilling-06.jpg", caption: "Website" },
      { type: "image", src: "/work/titan-drilling-07.jpg" },
    ],
    published: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "seed-black-diamond-marketplace",
    slug: "black-diamond-marketplace",
    title: "Black Diamond Marketplace",
    subtitle: "Product design / brand system / full-stack",
    occurred_on: "2026-05-01",
    client: "Black Diamond Marketplace",
    role: "Solo — brand, UX, UI, product, and engineering",
    summary:
      "I took a family oilfield brand and turned it into a working marketplace: identity, user flows, memberships, and an AI listing engine in one shipped product.",
    tags: ["product", "brand", "full-stack", "agentic"],
    accent: "#F15A24",
    specs: {
      Role: "Solo — brand, UX, UI, product, and engineering",
      Type: "Web application",
      Domain: "blackdiamondmkt.com",
      Stack: "Next.js · Auth · Supabase · Stripe · Anthropic API · Cursor",
    },
    cover_path: "/work/black-diamond-marketplace-01.png",
    blocks: [
      {
        type: "image",
        src: "/work/black-diamond-marketplace-01.png",
        caption:
          "Homepage — quiet field, one statement, two paths: Browse / List. Featured listings sit immediately below so the product proves it is real.",
      },
      {
        type: "text",
        title: "The problem",
        body: "Heavy equipment still moves the way it did twenty years ago.\n\nBuyers hunt through Facebook groups, auction sites, and word-of-mouth. Sellers write incomplete listings. Specs get lost. Brokers sit in the middle. Nobody can tell who is real.\n\nThe industry already had inventory. It did not have a product built in its own language.\n\nDesign problem: make a marketplace that feels like it was built by people who have stood in a yard in Odessa — not a generic classifieds template with an oil-rig stock photo.\n\nProduct problem: get a seller from “I have iron sitting” to a live, searchable listing in minutes, then get a serious buyer to the seller without a middleman.",
      },
      {
        type: "text",
        title: "The strategy",
        body: "Black Diamond already had a name, a diamond mark, and years of equipment credibility. The marketplace had to inherit that trust and then earn a new one: this software is as serious as the iron.\n\nPositioning, in one line:\nHuman-first. AI-supported. Built for operators, not for platforms.\n\nThat line drove every decision:\nOrange is the only loud color — used for money, action, and verification. Everything else stays quiet so photos of equipment can carry the page.\nCopy talks like the yard: “iron,” “list, publish, connect,” “field-grade.” No SaaS fluff.\nAI writes listings and extracts specs. Humans still close the deal. Inquiry is email and phone, not a chatbot pretending to be a buyer.\nFree to start (3 listings). Paid plans exist to fund reach, verification, and trust — not to lock the gate.\n\nWhat this is not\nNot a consumer auction. Not a broker desk. Not a redesign of Craigslist. Direct contact between verified sellers and buyers.",
      },
      {
        type: "text",
        title: "Brand system",
        body: "This is where the identity stops being a PDF and becomes code.\n\nLogo\nWordmark + diamond. Lives in the header at small size, watermarks listing photos where needed, and holds as a favicon. Never decoration. Always an identifier.\n\nColor\nink / near-black — type, logo, structure.\nsurface / off-white — page and cards.\nline / soft gray — borders, chips, filters, location pills.\naction / orange — the only accent: primary buttons, prices, “Most Popular,” step numbers.\nquiet / muted gray — meta text, categories, helper copy.\nRule: if it is not an action or a price, it is not orange.\n\nType\nHeavy grotesque headlines. Clean sans body. Hierarchy does the selling — title, price, location — so a listing card is readable on a phone in a truck.\n\nShape and space\nLarge radius cards. Generous padding. Pill chips for industry and location. The UI should feel like a well-built piece of equipment: tight tolerances, no extra chrome.\n\nVoice\nShort. Direct. Operator-grade.\n“The Trusted Marketplace For Heavy Equipment.”\n“List. Publish. Connect.”\n“Tell our AI what you have.”\n“Human-first, AI-supported — never the other way around.”\n\nDo\nLead with the equipment photo.\nPut price in orange.\nKeep verification visible (BD Verified, location, condition).\nUse industry categories operators already use.\n\nDon’t\nDecorate the UI with extra brand patterns that fight the photo.\nHide the price behind “Request a quote” unless the seller chose that.\nSound like a Silicon Valley marketplace.\nLet AI replace the phone call.",
      },
      {
        type: "image",
        src: "/work/black-diamond-marketplace-02.png",
        caption:
          "Search — filters first, cards second. Listing cards put price in the brand orange and bury category in small caps so a buyer can scan a yard’s worth of iron in seconds.",
      },
      {
        type: "image",
        src: "/work/black-diamond-marketplace-03.png",
        caption:
          "Listing detail — split layout: gallery left, decision panel right. Specs before the essay. Contact seller is the last beat, and it requires an account.",
      },
      {
        type: "image",
        src: "/work/black-diamond-marketplace-04.png",
        caption:
          "Pricing — four paid tiers plus Free. Orange only on the recommended path. Comparison is honest — gray X marks for what you do not get.",
      },
      {
        type: "text",
        title: "Buyer flow",
        body: "1. Land on homepage → search or “Browse Equipment”\n2. Filter by Industry / Category / Country / Sort\n3. Open a listing card (photo, category, title, price or “Contact for price,” location)\n4. Review specs, gallery, description\n5. Sign in or create an account\n6. Submit an inquiry → seller gets it directly (email / phone, human to human)\n\nWhy the account gate on inquiry: cuts anonymous noise and keeps the marketplace from turning into another open classifieds dump.",
      },
      {
        type: "text",
        title: "Seller flow",
        body: "1. Create account — free, no card required\n2. Describe the equipment in plain language → AI builds an SEO listing (title, specs, description)\n3. Add up to 20 photos → review → publish. Live immediately\n4. Receive inquiries on the listing → respond, negotiate, close on their terms",
      },
      {
        type: "text",
        title: "Membership",
        body: "Free — $0 — 3 listings — Get started\nStarter — $299/mo — 15 listings — BD Verified, AI listings, directory\nPro — $699/mo — 40 listings — Analytics + newsletter feature\nMax — $999/mo — Unlimited — Spotlight, blast, priority support\nEnterprise — Custom — Unlimited + seats — Multi-location, roles, billing\n\nAnnual billing: two months free. Payments via Stripe.",
      },
      {
        type: "image",
        src: "/work/black-diamond-marketplace-05.png",
        caption:
          "How it works — black hero for gravity, then a numbered seller path. AI is step 2, not the headline of the company.",
      },
      {
        type: "text",
        title: "Architecture",
        body: "Client — Next.js App Router.\nPublic: home, search, listings/[slug], about, pricing, how-it-works, journal, sellers.\nDashboard: seller tools, listings CRUD, membership.\nAuth: login / signup.\n\nUnderneath: auth and sessions (accounts, roles, BD Verified); listings and media (specs, photos, search indexes); payments via Stripe (Free / Starter / Pro / Max / Enterprise).\n\nWhat the agentic layer actually does\nTurns a seller’s rough description into a structured listing.\nPulls manufacturer, model, hours, condition, and category when possible.\nWrites search-friendly copy in oilfield language.\nDoes not close the deal. That stays human.\n\nCore objects\nUser (guest → member → verified seller / org seat)\nListing (media, specs, price or RFQ, location, status)\nInquiry (buyer → seller, gated by auth)\nMembership (plan, listing cap, badges, placements)\nJournal article (content / SEO / trust)",
      },
      {
        type: "text",
        title: "Decisions",
        body: "Photos own the UI.\nHeavy equipment is judged by the iron, not the chrome. The brand recedes so the asset can sell.\n\nPrice is a brand color.\nOrange is reserved for action and money. A recruiter can see that rule on every screen.\n\nAI is a tool, not the product.\nThe product is trust + speed. AI removes the blank listing form. Verification and direct contact do the rest.\n\nFree tier exists on purpose.\nThree listings with no card. The brand cannot preach “built for operators” and then meter the first step.\n\nTwo Black Diamond entries, one story.\nDrilling = the identity. Marketplace = the identity encoded as software. Same system, second chapter.",
      },
      {
        type: "text",
        title: "See it live",
        body: "The marketplace is live and working.\n\nSearch listings, open a product page, walk the seller flow, and check the membership plans at blackdiamondmkt.com.\n\nThat’s the result. The brand system is in the product, the product is on the internet, and you can use it.",
      },
    ],
    published: true,
    created_at: now,
    updated_at: now,
  },
];
